### ISSUE TITLE
Website for configuration stuff?

### ISSUE THREAD

**Issue by themaxdavitt** [nationalcollegiateesports/discord-bot#6]
Provide an interface for server owners/admins to change settings for their server without needing to contact the bot admins.

**Comment by eritbh** [comment]
My usual method of tackling stuff like this is to make a JSON API that authenticate users through Discord and read/update the database, then write a web application that talks to the API. [Express](https://expressjs.com) is a good web server library that can be used for the API, and [Vue](https://vuejs.org) has been my favorite frontend library for some time now. [Bulma](https://bulma.io) is a nice, customizable CSS framework, and it has a Vue-specific component library, [Buefy](https://buefy.org).

I'd probably be basing a lot of the code for this off my work on https://github.com/r-anime/discord-mod-bot which has its web interface in the "web" directory. (That repo uses a module called `polka` instead of express for its server; they work almost identically, but for this project I think I'd prefer express for its maturity and wider adoption.)

**Comment by themaxdavitt** [comment]
Sounds like a plan to me - Express, Vue, and Bulma/Buefy are all great choices IMO.

**Comment by themaxdavitt** [comment]
Also, closing this in favor of #9 also.
